name: Run Unit Test For SDKs

on:
  pull_request:
    branches:
      - main
    paths:
      - sdks/**
      - .github/workflows/tool-test-sdks.yaml

concurrency:
  group: sdk-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: unit test for Node.js SDK
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    defaults:
      run:
        working-directory: sdks/nodejs-client

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS ${{ matrix.node-version }} and Install Yarn dependencies
        uses: .github/actions/setup-yarn
        with:
          node-version: ${{ matrix.node-version }}
          yarn-lockfile: sdks/nodejs-client/yarn.lock

      - name: Test
        run: yarn test
