name: Web Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - web/**
      - .github/workflows/web-tests.yml

concurrency:
  group: web-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Web Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            web/**
            .github/workflows/web-tests.yml

      - name: Setup NodeJS and Install Yarn dependencies
        uses: .github/actions/setup-yarn
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          yarn-lockfile: web/yarn.lock

      - name: Run tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn test
